In [17]:
import numpy as np

def tensor_product(*vectors):
    result = vectors[0]
    for vector in vectors[1:]:
        result = np.kron(result, vector)
    return result

def tensor_product_rec(num_vecs, curr_num_vecs, curr_vec, vec_options):
    if curr_num_vecs == num_vecs:
        print("Tensor product of A x B x C x D:")
        print(curr_vec)
        return
    else:
        count = 0
        for i in vec_options:
            result = np.kron(curr_vec, i)
            if count == 0:
                print(f"{curr_vec} \otimes |0>")
            elif count == 1:
                print(f"{curr_vec} \otimes |1>")
            tensor_product_rec(num_vecs, curr_num_vecs + 1, result, vec_options)
            result = None
            count += 1

# Example vectors A, B, C, and D (2x1 column vectors)
zero_qub = np.array([[1], [0]])
one_qub = np.array([[0], [1]])
vec_options = np.array([zero_qub, one_qub])

#Test of tensor_product_rec
tensor_product_rec(4, 1, zero_qub, vec_options)
tensor_product_rec(4, 1, one_qub, vec_options)

# A = zero_qub
# B = zero_qub
# C = zero_qub
# D = zero_qub

# # Calculate tensor product A x B x C x D
# result = tensor_product(A, B, C, D)
# print("Tensor product of A x B x C x D:")
# print(result)

# A = zero_qub
# B = zero_qub
# C = zero_qub
# D = one_qub

# # Calculate tensor product A x B x C x D
# result = tensor_product(A, B, C, D)
# print("Tensor product of A x B x C x D:")
# print(result)

# A = zero_qub
# B = zero_qub
# C = one_qub
# D = zero_qub

# # Calculate tensor product A x B x C x D
# result = tensor_product(A, B, C, D)
# print("Tensor product of A x B x C x D:")
# print(result)


[[1]
 [0]] \otimes |0>
[[1]
 [0]
 [0]
 [0]] \otimes |0>
[[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]] \otimes |0>
Tensor product of A x B x C x D:
[[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]] \otimes |1>
Tensor product of A x B x C x D:
[[0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[1]
 [0]
 [0]
 [0]] \otimes |1>
[[0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]] \otimes |0>
Tensor product of A x B x C x D:
[[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]] \otimes |1>
Tensor product of A x B x C x D:
[[0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[1]
 [0]] \otimes |1>
[[0]
 [1]
 [0]
 [0]] \otimes |0>
[[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]] \otimes |0>
Tensor product of A x B x C x D:
[[0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[0]
 [0]
 [1]
 [0]
