In [37]:
## QUESTION 3 c) ##

from qiskit import QuantumCircuit, transpile
from qiskit_aer import Aer
from qiskit.visualization import array_to_latex

# Create the circuit 
# QuantumCircuit(4) -> 4 qubits in the circuit
# "cx" = "CNOT", "x" = "Pauli X" = the quantum equivalent of a classical "NOT" gate
qc = QuantumCircuit(4)
qc.cx(0, 2)
qc.cx(1, 3)
qc.cx(3, 2)
qc.cx(0, 3)
qc.x(3)

# Transpile the circuit for the Qiskit UnitarySimulator
qc_transpiled = transpile(qc, Aer.get_backend('unitary_simulator'))

# Get the unitary matrix
simulator = Aer.get_backend('unitary_simulator')
result = simulator.run(qc_transpiled).result()
unitary = result.get_unitary()

# Display the unitary matrix
print("Unitary Matrix:")
print(unitary)

array_to_latex(unitary, prefix="\\text{Circuit Matrix} = ")
# ^^This for some reason doesn't show all the nontrivial parts of the matrix, but hey, I
# don't know, maybe you'll want it just to make the parts of it that do print look a little 
# nicer than the wall of text that the "print(unitary)" statement outputs. :)


Unitary Matrix:
Operator([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
           0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j,
           0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j,
           0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
           0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
           1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
           0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
   

<IPython.core.display.Latex object>

In [38]:
## QUESTION 3 c) continued ##

print(qc.draw())

                              
q_0: ──■──────────────■───────
       │              │       
q_1: ──┼────■─────────┼───────
     ┌─┴─┐  │  ┌───┐  │       
q_2: ┤ X ├──┼──┤ X ├──┼───────
     └───┘┌─┴─┐└─┬─┘┌─┴─┐┌───┐
q_3: ─────┤ X ├──■──┤ X ├┤ X ├
          └───┘     └───┘└───┘


In [39]:
## QUESTION 3 c) continued ##

import numpy as np

unitary_np = np.array(unitary)
unitary_np.astype(int)

C:\Users\caleb\AppData\Local\Temp\ipykernel_43420\2018507138.py:6: ComplexWarning: Casting complex values to real discards the imaginary part
  unitary_np.astype(int)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [40]:
## QUESTION 3 d) ##

import numpy as np

# Input state (need it to be 16x1)
# 0.5(|00>-|01>+|10>-|11>) = ([0.5,-0.5,0.5,-0.5]), and then since this is part of a 4-qubit state vector,
# where the last two qubits - the ancilla qubits - are always |0>, make it one
zero_qub = np.array([[1], [0]]) # column vector
input_state = np.kron(np.kron(np.array([0.5,-0.5,0.5,-0.5]).reshape(-1, 1), zero_qub), zero_qub) # <- have to reshape the input state into a column vector

# Calculate the output state using matrix multiplication
output_state = np.dot(unitary, input_state)

print(output_state)

[[-0.5+0.j]
 [ 0. +0.j]
 [ 0. +0.j]
 [ 0. +0.j]
 [ 0.5+0.j]
 [ 0. +0.j]
 [ 0. +0.j]
 [ 0. +0.j]
 [ 0.5+0.j]
 [ 0. +0.j]
 [ 0. +0.j]
 [ 0. +0.j]
 [-0.5+0.j]
 [ 0. +0.j]
 [ 0. +0.j]
 [ 0. +0.j]]


In [41]:
## QUESTION 3 e), assuming Hadamard gate applied to only qubits "a" and "b" ##

import numpy as np

zero_qub = np.array([[1], [0]]) # column vector

print(2**(-0.5)) #DEBUG

hadamard_gate = np.array([[2**(-0.5), 2**(-0.5)], [2**(-0.5), -(2**(-0.5))]])

hadamard_tensor_prod = np.kron(hadamard_gate, hadamard_gate)

print("H \otimes H:") # as in, the tensor product of two Hadamard gates
print(hadamard_tensor_prod)

input_state = np.kron(np.kron(np.dot(hadamard_tensor_prod, np.array([1,0,0,0]).reshape(-1, 1)), zero_qub), zero_qub)

# Calculate the output state using matrix multiplication
output_state = np.dot(unitary, input_state)

print(output_state)

0.7071067811865476
H \otimes H:
[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]
[[0.5+0.j]
 [0. +0.j]
 [0. +0.j]
 [0. +0.j]
 [0.5+0.j]
 [0. +0.j]
 [0. +0.j]
 [0. +0.j]
 [0.5+0.j]
 [0. +0.j]
 [0. +0.j]
 [0. +0.j]
 [0.5+0.j]
 [0. +0.j]
 [0. +0.j]
 [0. +0.j]]


In [42]:
## QUESTION 3 e), assuming Hadamard gate applied to qubits "a" and "b" during the circuit ##

from qiskit import QuantumCircuit, transpile
from qiskit_aer import Aer
from qiskit.visualization import array_to_latex

# Create the circuit
qc2 = QuantumCircuit(4)
qc2.h(0)
qc2.h(1)
qc2.cx(0, 2)
qc2.cx(1, 3)
qc2.cx(3, 2)
qc2.cx(0, 3)
qc2.x(3)

# Transpile the circuit for the UnitarySimulator
qc2_transpiled = transpile(qc2, Aer.get_backend('unitary_simulator'))

# Get the unitary matrix
simulator = Aer.get_backend('unitary_simulator')
result2 = simulator.run(qc2_transpiled).result()
unitary2 = result2.get_unitary()

# Display the unitary matrix
print("Unitary Matrix:")
print(unitary2)

array_to_latex(unitary2, prefix="\\text{Circuit Matrix} = ")


Unitary Matrix:
Operator([[ 0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
            0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
            0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
            0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
            0.5+0.0000000e+00j,  0.5-6.1232340e-17j,  0.5-6.1232340e-17j,
            0.5-1.2246468e-16j],
          [ 0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
            0. +0.0000000e+00j,  0.5+0.0000000e+00j, -0.5+6.1232340e-17j,
            0.5-6.1232340e-17j, -0.5+1.2246468e-16j,  0. +0.0000000e+00j,
            0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
            0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
            0. +0.0000000e+00j],
          [ 0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
            0. +0.0000000e+00j,  0.5+0.0000000e+00j,  0.5-6.1232340e-17j,
           -0.5+6.1232340e-17j

<IPython.core.display.Latex object>

In [43]:
## QUESTION 3 e), assuming Hadamard gate applied to qubits "a" and "b" during the circuit (continued...) ##

import numpy as np

unitary2_np = np.array(unitary2)
unitary2_np.astype(complex)

array([[ 0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
         0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
         0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
         0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
         0.5+0.0000000e+00j,  0.5-6.1232340e-17j,  0.5-6.1232340e-17j,
         0.5-1.2246468e-16j],
       [ 0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
         0. +0.0000000e+00j,  0.5+0.0000000e+00j, -0.5+6.1232340e-17j,
         0.5-6.1232340e-17j, -0.5+1.2246468e-16j,  0. +0.0000000e+00j,
         0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
         0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
         0. +0.0000000e+00j],
       [ 0. +0.0000000e+00j,  0. +0.0000000e+00j,  0. +0.0000000e+00j,
         0. +0.0000000e+00j,  0.5+0.0000000e+00j,  0.5-6.1232340e-17j,
        -0.5+6.1232340e-17j, -0.5+1.2246468e-16j,  0. +0.0000000e+00j,
         0. +0.00

In [44]:
## QUESTION 3 e), assuming Hadamard gate applied to qubits "a" and "b" during the circuit (continued 2...) ##

zero_qub = np.array([[1], [0]]) # column vector

input_state = np.kron(np.kron(np.array([1,0,0,0]).reshape(-1, 1), zero_qub), zero_qub)

# Calculate the output state using matrix multiplication
output_state = np.dot(unitary2, input_state)

print(output_state)

[[0. +0.j]
 [0. +0.j]
 [0. +0.j]
 [0. +0.j]
 [0. +0.j]
 [0.5+0.j]
 [0.5+0.j]
 [0. +0.j]
 [0.5+0.j]
 [0. +0.j]
 [0. +0.j]
 [0.5+0.j]
 [0. +0.j]
 [0. +0.j]
 [0. +0.j]
 [0. +0.j]]


In [16]:
# input_state = np.dot(hadamard_tensor_prod, np.array([1,0,0,0]).reshape(-1, 1))

# # Calculate the output state using matrix multiplication
# output_state = np.dot(unitary, input_state)

## TEST ##

ValueError: shapes (16,16) and (4,1) not aligned: 16 (dim 1) != 4 (dim 0)